pipeline {
    agent any
    tools {
    maven 'Maven-3.8.7'  // this name matches the Global Tool Configuration entry
    }
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Complete') { 
            steps {
                echo 'Job Complete!'
            }
        }
    }
}
